// Generates 15k+ unique long-tail B2B donkey-milk keywords per language.
// Output: client/public/seo/keywords.{en,fr,it,de}.json  (full indexable lists)
//         client/public/seo/meta.{en,fr,it,de}.json      (compact subset for <meta keywords>)
import fs from "fs";
import path from "path";

const OUT = path.resolve("client/public/seo");
fs.mkdirSync(OUT, { recursive: true });

// ---- language-specific term banks ----
const B = {
  en: {
    product: [
      "donkey milk",
      "donkey milk powder",
      "freeze dried donkey milk powder",
      "raw donkey milk",
      "spray dried donkey milk",
      "donkey colostrum",
      "ass milk",
      "ass milk powder",
      "equine milk",
      "fresh donkey milk",
      "bulk donkey milk",
      "wholesale donkey milk",
      "organic donkey milk",
      "donkey whey",
      "lyophilized donkey milk",
    ],
    form: [
      "powder",
      "bulk powder",
      "private label powder",
      "OEM powder",
      "sachet",
      "drum",
      "bag",
      "liquid",
      "concentrate",
      "capsule",
      "softgel",
      "raw material",
    ],
    industry: [
      "cosmetics",
      "skincare",
      "soap",
      "pharmaceutical",
      "nutraceutical",
      "infant formula",
      "food",
      "beverage",
      "supplement",
      "anti aging",
      "dermatology",
      "spa",
      "wellness",
      "pet food",
      "animal nutrition",
      "clinical nutrition",
      "research",
      "laboratory",
      "white label brand",
      "OEM manufacturer",
    ],
    use: [
      "moisturizer",
      "face cream",
      "serum",
      "lotion",
      "cleanser",
      "mask",
      "anti wrinkle",
      "baby formula",
      "capsule",
      "tablet",
      "drink",
      "yogurt",
      "cheese",
      "tonic",
      "shampoo",
    ],
    cert: [
      "FSSAI",
      "ISO",
      "HACCP",
      "IEC",
      "organic",
      "halal",
      "GMP",
      "third party tested",
      "lab tested",
      "certified",
    ],
    attr: [
      "natural",
      "hypoallergenic",
      "pure",
      "premium",
      "high protein",
      "low lactose",
      "antibacterial",
      "rich in lysozyme",
      "cold chain",
      "shelf stable",
      "export grade",
    ],
    geo: [
      "India",
      "Pune",
      "Maharashtra",
      "Mumbai",
      "Delhi",
      "Bangalore",
      "UAE",
      "Dubai",
      "Germany",
      "France",
      "Italy",
      "Europe",
      "Korea",
      "Japan",
      "USA",
      "UK",
      "Asia",
      "GCC",
      "Middle East",
      "Africa",
    ],
    intent: [
      "supplier",
      "manufacturer",
      "exporter",
      "wholesaler",
      "distributor",
      "factory",
      "company",
      "vendor",
      "dealers",
      "bulk buy",
      "price",
      "quote",
      "for sale",
      "near me",
      "online",
      "private label",
      "OEM",
    ],
    buyer: [
      "B2B",
      "brand",
      "formulator",
      "distributor",
      "importer",
      "retailer",
      "pharma company",
      "cosmetic brand",
      "startup",
      "enterprise",
      "buyer",
    ],
  },
  fr: {
    product: [
      "lait d'ânesse",
      "poudre de lait d'ânesse",
      "poudre de lait d'ânesse lyophilisée",
      "lait d'ânesse cru",
      "lait d'ânesse en poudre",
      "lait d'ânesse frais",
      "lait d'ânesse biologique",
      "lait d'ânesse en vrac",
      "lait d'ânesse grossiste",
    ],
    form: [
      "poudre",
      "poudre en vrac",
      "marque privée poudre",
      "OEM poudre",
      "sachet",
      "fût",
      "sac",
      "liquide",
      "concentré",
      "gélule",
      "matière première",
    ],
    industry: [
      "cosmétique",
      "soin de la peau",
      "savon",
      "pharmaceutique",
      "nutraceutique",
      "lait infantile",
      "alimentaire",
      "boisson",
      "complément",
      "anti âge",
      "dermatologie",
      "spa",
      "bien être",
      "aliment pour animaux",
      "nutrition clinique",
      "recherche",
      "laboratoire",
      "marque privée",
      "fabricant OEM",
    ],
    use: [
      "hydratant",
      "crème visage",
      "sérum",
      "lotion",
      "nettoyant",
      "masque",
      "anti rides",
      "lait bébé",
      "gélule",
      "comprimé",
      "boisson",
      "yaourt",
      "tonique",
      "shampooing",
    ],
    cert: [
      "FSSAI",
      "ISO",
      "HACCP",
      "IEC",
      "biologique",
      "halal",
      "GMP",
      "testé tiers",
      "testé labo",
      "certifié",
    ],
    attr: [
      "naturel",
      "hypoallergénique",
      "pur",
      "premium",
      "riche en protéines",
      "faible lactose",
      "antibactérien",
      "riche en lysozyme",
      "chaîne du froid",
      "stable",
      "qualité export",
    ],
    geo: [
      "Inde",
      "Pune",
      "Maharashtra",
      "Mumbai",
      "Delhi",
      "Bangalore",
      "EAU",
      "Dubaï",
      "Allemagne",
      "France",
      "Italie",
      "Europe",
      "Corée",
      "Japon",
      "USA",
      "Royaume Uni",
      "Asie",
      "CGP",
      "Moyen Orient",
      "Afrique",
    ],
    intent: [
      "fournisseur",
      "fabricant",
      "exportateur",
      "grossiste",
      "distributeur",
      "usine",
      "société",
      "revendeur",
      "achat en gros",
      "prix",
      "devis",
      "à vendre",
      "près de moi",
      "en ligne",
      "marque privée",
      "OEM",
    ],
    buyer: [
      "B2B",
      "marque",
      "formulateur",
      "distributeur",
      "importateur",
      "détaillant",
      "société pharma",
      "marque cosmétique",
      "startup",
      "entreprise",
      "acheteur",
    ],
  },
  it: {
    product: [
      "latte d'asina",
      "polvere di latte d'asina",
      "polvere di latte d'asina liofilizzata",
      "latte d'asina crudo",
      "latte d'asina in polvere",
      "latte d'asina fresco",
      "latte d'asina biologico",
      "latte d'asina all'ingrosso",
      "latte d'asina bulk",
    ],
    form: [
      "polvere",
      "polvere all'ingrosso",
      "marca privata polvere",
      "OEM polvere",
      "bustina",
      "fusto",
      "sacco",
      "liquido",
      "concentrato",
      "capsula",
      "materia prima",
    ],
    industry: [
      "cosmetico",
      "cura della pelle",
      "sapone",
      "farmaceutico",
      "nutraceutico",
      "latte infantile",
      "alimentare",
      "bevanda",
      "integratore",
      "anti età",
      "dermatologia",
      "spa",
      "benessere",
      "cibo per animali",
      "nutrizione clinica",
      "ricerca",
      "laboratorio",
      "marca privata",
      "fabbricante OEM",
    ],
    use: [
      "idratante",
      "crema viso",
      "siero",
      "lozione",
      "detergente",
      "maschera",
      "anti rughe",
      "latte bimbo",
      "capsula",
      "compressa",
      "bevanda",
      "yogurt",
      "tonico",
      "shampoo",
    ],
    cert: [
      "FSSAI",
      "ISO",
      "HACCP",
      "IEC",
      "biologico",
      "halal",
      "GMP",
      "testato terzi",
      "testato lab",
      "certificato",
    ],
    attr: [
      "naturale",
      "ipocompatibile",
      "puro",
      "premium",
      "ricco di proteine",
      "basso lattosio",
      "antibatterico",
      "ricco di lisozima",
      "catena del freddo",
      "stabile",
      "grado export",
    ],
    geo: [
      "India",
      "Pune",
      "Maharashtra",
      "Mumbai",
      "Delhi",
      "Bangalore",
      "EAU",
      "Dubai",
      "Germania",
      "Francia",
      "Italia",
      "Europa",
      "Corea",
      "Giappone",
      "USA",
      "Regno Unito",
      "Asia",
      "GCC",
      "Medio Oriente",
      "Africa",
    ],
    intent: [
      "fornitore",
      "fabbricante",
      "esportatore",
      "grossista",
      "distributore",
      "fabbrica",
      "azienda",
      "rivenditore",
      "acquisto all'ingrosso",
      "prezzo",
      "preventivo",
      "in vendita",
      "vicino a me",
      "online",
      "marca privata",
      "OEM",
    ],
    buyer: [
      "B2B",
      "marca",
      "formulatore",
      "distributore",
      "importatore",
      "rivenditore",
      "azienda pharma",
      "marca cosmetica",
      "startup",
      "impresa",
      "acquirente",
    ],
  },
  de: {
    product: [
      "eselmilch",
      "eselmilchpulver",
      "gefriertrocknetes eselmilchpulver",
      "rohe eselmilch",
      "eselmilch pulver",
      "frische eselmilch",
      "bio eselmilch",
      "eselmilch großhandel",
      "eselmilch bulk",
    ],
    form: [
      "pulver",
      "pulver großhandel",
      "privatlabel pulver",
      "OEM pulver",
      "beutel",
      "fass",
      "sack",
      "flüssig",
      "konzentrat",
      "kapsel",
      "rohstoff",
    ],
    industry: [
      "kosmetik",
      "hautpflege",
      "seife",
      "pharmazeutisch",
      "nutraceutical",
      "säuglingsmilch",
      "lebensmittel",
      "getränk",
      "nahrungsergänzung",
      "anti aging",
      "dermatologie",
      "spa",
      "wellness",
      "tierfutter",
      "klinische ernährung",
      "forschung",
      "labor",
      "privatmarke",
      "OEM hersteller",
    ],
    use: [
      "feuchtigkeitscreme",
      "gesichtscreme",
      "serum",
      "lotion",
      "reiniger",
      "maske",
      "anti falten",
      "babymilch",
      "kapsel",
      "tablette",
      "getränk",
      "joghurt",
      "tonikum",
      "shampoo",
    ],
    cert: [
      "FSSAI",
      "ISO",
      "HACCP",
      "IEC",
      "bio",
      "halal",
      "GMP",
      "drittgetestet",
      "labortest",
      "zertifiziert",
    ],
    attr: [
      "natürlich",
      "hypoallergen",
      "rein",
      "premium",
      "eiweißreich",
      "laktosearm",
      "antibakteriell",
      "lysozymreich",
      "kältekette",
      "stabil",
      "exportqualität",
    ],
    geo: [
      "Indien",
      "Pune",
      "Maharashtra",
      "Mumbai",
      "Delhi",
      "Bangalore",
      "VAE",
      "Dubai",
      "Deutschland",
      "Frankreich",
      "Italien",
      "Europa",
      "Korea",
      "Japan",
      "USA",
      "UK",
      "Asien",
      "GCC",
      "Naher Osten",
      "Afrika",
    ],
    intent: [
      "lieferant",
      "hersteller",
      "exporteur",
      "großhändler",
      "distributor",
      "fabrik",
      "firma",
      "händler",
      "großbestellung",
      "preis",
      "angebot",
      "zum verkauf",
      "in der nähe",
      "online",
      "privatlabel",
      "OEM",
    ],
    buyer: [
      "B2B",
      "marke",
      "formulier",
      "distributor",
      "importeur",
      "einzelhändler",
      "pharma firma",
      "kosmetikmarke",
      "startup",
      "unternehmen",
      "käufer",
    ],
  },
};

const BRAND = "Rudra Dairy & Farm";

function combos(L) {
  const b = B[L];
  const out = new Set();
  const add = s => {
    s = s.trim().replace(/\s+/g, " ");
    if (s.length >= 3) out.add(s);
  };
  // 1-term
  for (const x of [...b.product, ...b.industry, ...b.intent]) add(x);
  // 2-term: product+form, product+industry, product+attr, product+cert, industry+use, geo+intent
  for (const p of b.product) for (const f of b.form) add(`${p} ${f}`);
  for (const p of b.product) for (const i of b.industry) add(`${p} ${i}`);
  for (const p of b.product) for (const a of b.attr) add(`${a} ${p}`);
  for (const p of b.product) for (const c of b.cert) add(`${p} ${c}`);
  for (const i of b.industry) for (const u of b.use) add(`${i} ${u}`);
  for (const g of b.geo) for (const it of b.intent) add(`${g} ${it}`);
  for (const p of b.product) for (const it of b.intent) add(`${p} ${it}`);
  for (const i of b.industry) for (const it of b.intent) add(`${i} ${it}`);
  // 3-term: product+form+intent, product+attr+geo, product+industry+geo, brand+product
  for (const p of b.product)
    for (const f of b.form) for (const it of b.intent) add(`${p} ${f} ${it}`);
  for (const p of b.product)
    for (const a of b.attr) for (const g of b.geo) add(`${a} ${p} ${g}`);
  for (const p of b.product)
    for (const i of b.industry) for (const g of b.geo) add(`${p} ${i} ${g}`);
  for (const p of b.product) add(`${BRAND} ${p}`);
  for (const i of b.industry) for (const b2 of b.buyer) add(`${b2} ${i}`);
  for (const p of b.product) for (const b2 of b.buyer) add(`${b2} ${p}`);
  // 4-term long-tail
  for (const p of b.product)
    for (const f of b.form)
      for (const c of b.cert)
        for (const it of b.intent) add(`${p} ${f} ${c} ${it}`);
  for (const p of b.product)
    for (const a of b.attr)
      for (const g of b.geo)
        for (const it of b.intent) add(`${a} ${p} ${g} ${it}`);
  return out;
}

const TARGET = 15600;
let report = [];
for (const L of ["en", "fr", "it", "de"]) {
  let set = combos(L);
  // pad with numbered long-tail variants if needed (should not be needed)
  let i = 0;
  while (set.size < TARGET) {
    for (const p of B[L].product)
      for (const g of B[L].geo)
        for (const it of B[L].intent) {
          set.add(
            `${p} ${g} ${it} ${B[L].attr[i % B[L].attr.length]} ${B[L].buyer[(i + 1) % B[L].buyer.length]}`
          );
          i++;
          if (set.size >= TARGET) break;
        }
    if (i > 5000) break;
  }
  const arr = [...set];
  fs.writeFileSync(path.join(OUT, `keywords.${L}.json`), JSON.stringify(arr));
  // compact meta subset — a practical cap of ~150 keywords keeps the
  // injected <meta keywords> tag small (a few KB) instead of 30KB+.
  // Google ignores meta-keywords; this is a Bing/legacy relevance hint only.
  const META_CAP = 150;
  const meta = arr.slice(0, META_CAP).join(", ");
  fs.writeFileSync(
    path.join(OUT, `meta.${L}.json`),
    JSON.stringify({ keywords: meta })
  );
  report.push(`${L}: ${arr.length} keywords (meta head ${meta.length} chars)`);
}
console.log(report.join("\n"));
console.log("\nWrote to", OUT);
