// Runtime loader for per-language long-tail keyword meta strings.
// Keywords live in /seo/meta.<lang>.json (generated by scripts/gen_keywords.mjs)
// so they NEVER bloat the JS bundle (Core Web Vitals safe).
import type { Lang } from "./languages";
import { useI18n } from "./index";
import { useEffect, useState } from "react";

const cache: Partial<Record<Lang, string>> = {};

export async function loadMetaKeywords(lang: Lang): Promise<string> {
  if (cache[lang]) return cache[lang] as string;
  try {
    const res = await fetch(`/seo/meta.${lang}.json`);
    if (!res.ok) return "";
    const data = (await res.json()) as { keywords?: string };
    cache[lang] = data.keywords || "";
    return cache[lang] as string;
  } catch {
    return "";
  }
}

/** Synchronously read a cached value if already loaded (no async needed on repeat renders). */
export function getCachedMetaKeywords(lang: Lang): string {
  return cache[lang] || "";
}

/** Hook: returns the per-language long-tail keyword string for <meta keywords>. */
export function usePageKeywords(): string {
  const { lang } = useI18n();
  const [kw, setKw] = useState(() => getCachedMetaKeywords(lang));
  useEffect(() => {
    let alive = true;
    if (cache[lang]) {
      setKw(cache[lang] as string);
      return;
    }
    loadMetaKeywords(lang).then(v => {
      if (alive) setKw(v);
    });
    return () => {
      alive = false;
    };
  }, [lang]);
  return kw;
}
